language: cpp

compiler: 
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8 g++-4.8
      - clang

install:
  - sudo apt-get -qq install gcc-4.8-multilib g++-4.8-multilib
  - if [ "$CC" == "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi
  - export CX=$CXX
  - $CX --version

script:
  - cd ./build
  - make debug=1 && make
  - ./bin/debug/$CC/ut-test

notifications:
  slack:
    on_success: never
    on_failure: never
