sudo: false
language: cpp

compiler: 
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

install:
  - if [ "$CC" == "gcc" ]; then apt-get install gcc-4.8-multilib g++-4.8-multilib
  - if [ "$CC" == "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi
  - CX=$CXX
  - $CX --version

script: cd ./build && make
