language: cpp

compiler: 
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

install:
  - if [ "$CC" == "gcc" ]; then sudo apt-get -qq install gcc-4.8-multilib g++-4.8-multilib; fi
  - if [ "$CC" == "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi
  - export CX=$CXX
  - $CX --version
  - if [ "$CC" == "clang" ]; then export THIRD_PATH="/usr/include/c++/4.8 -I/usr/include/i386-linux-gnu/c++/4.8"; fi
  - sudo apt-get install mlocate
  - sudo updatedb
  - sudo locate c++config.h

script: cd ./build && make
