language: cpp

compiler: 
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

install:
  - sudo apt-get -qq install gcc-4.8-multilib g++-4.8-multilib
  - if [ "$CC" == "clang" ]; then export THIRD_PATH="/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8"; fi
  - if [ "$CC" == "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi
  - export CX=$CXX
  - $CX --version

script: cd ./build && make
