language: cpp

compiler: 
  - gcc
  - clang

install:
  - if [ "$CC" == "gcc" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CC" == "gcc" ]; then sudo apt-get -qq update; fi
  - if [ "$CC" == "gcc" ]; then sudo apt-get -qq install gcc-4.8 g++-4.8; fi
  - if [ "$CC" == "gcc" ]; then sudo apt-get -qq install gcc-4.8-multilib g++-4.8-multilib; fi
  - if [ "$CC" == "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8; fi
  - CX=$CXX
  - $CC --version
  - $CX --version

script: cd ./build && make
